### ISSUE TITLE
Integration not working with HA 2025.6

### ISSUE THREAD

**Issue by poudenes** [twrecked/hass-momentary#49]
Hi All,

The integration is stop working with new HA 2025.6

Debug log:
```
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
2025-06-12 08:48:52.924 DEBUG (MainThread) [custom_components.momentary] async setup {'file_name': '/config/integrations/momentary.yaml', 'group_name': 'Switches', 'switches': ['f5445eb4-6123-4704-ae53-ddd88f7f4933.momentary', '02b3c1bc-13f1-4e38-b0f5-4b8a8df94e18.momentary', '18e4ef76-137a-4e45-90c1-c4fbc56ec9f2.momentary', '553cb066-0315-459c-9ec1-042565b72de1.momentary', '99437777-d665-4dc9-8b5e-294611b647db.momentary']}
2025-06-12 08:48:52.924 DEBUG (MainThread) [custom_components.momentary.cfg] _async_load_yaml1 file_name for /config/.storage/momentary.meta.json
2025-06-12 08:48:52.927 DEBUG (MainThread) [custom_components.momentary.cfg] _async_load_yaml2 file_name for /config/.storage/momentary.meta.json
2025-06-12 08:48:52.930 DEBUG (MainThread) [custom_components.momentary.cfg] _async_load_yaml3 file_name for /config/.storage/momentary.meta.json
2025-06-12 08:48:52.931 DEBUG (MainThread) [custom_components.momentary.cfg] _async_load_yaml1 file_name for /config/integrations/momentary.yaml
2025-06-12 08:48:52.933 DEBUG (MainThread) [custom_components.momentary.cfg] _async_load_yaml2 file_name for /config/integrations/momentary.yaml
2025-06-12 08:48:52.933 DEBUG (MainThread) [custom_components.momentary.cfg] _async_load_yaml3 file_name for /config/integrations/momentary.yaml
2025-06-12 08:48:52.936 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary Peter Early Up/172f520c-a166-4252-88fc-579f98236a92.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary Peter Early Up/switch.momentary_peter_early_up
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary Early Sleep/6b00964b-bd44-4b1c-a92b-2895a6747766.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary Early Sleep/switch.momentary_early_sleep
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary Guests/e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary Guests/switch.momentary_guests
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary For testing/0c9dfc91-6886-4962-872e-1259f7263bf1.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary For testing/switch.momentary_for_testing
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary Scene Morning/079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary Scene Morning/switch.momentary_scene_morning
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Backup full/894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Backup full/switch.momentary_mvps_backup_full
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Update blacklist/a0a182be-735d-4122-aa22-9d54d0806022.momentary
2025-06-12 08:48:52.937 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Update blacklist/switch.momentary_mvps_update_blacklist
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS apt update/a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS apt update/switch.momentary_mvps_apt_update
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS ipset abuseipdb/33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS ipset abuseipdb/switch.momentary_mvps_ipset_abuseipdb
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Umount NAS/cce01948-a4ce-41da-8906-7ef99fdad568.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Umount NAS/switch.momentary_mvps_umount_nas
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Backup db/9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Backup db/switch.momentary_mvps_backup_db
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Backup ispconfig/594b8a78-3786-48f7-bf24-f55e49451da0.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Backup ispconfig/switch.momentary_mvps_backup_ispconfig
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Backup vmail/16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Backup vmail/switch.momentary_mvps_backup_vmail
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS clearlog/51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS clearlog/switch.momentary_mvps_clearlog
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with device Momentary MVPS Rspamd learn/6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] working with entity Momentary MVPS Rspamd learn/switch.momentary_mvps_rspamd_learn
2025-06-12 08:48:52.938 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary Peter Early Up
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary Early Sleep
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary Guests
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary For testing
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary Scene Morning
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Backup full
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Update blacklist
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS apt update
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS ipset abuseipdb
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Umount NAS
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Backup db
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Backup ispconfig
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Backup vmail
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS clearlog
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] still using Momentary MVPS Rspamd learn
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] dump(load):devices={'172f520c-a166-4252-88fc-579f98236a92.momentary': 'Momentary Peter Early Up', '6b00964b-bd44-4b1c-a92b-2895a6747766.momentary': 'Momentary Early Sleep', 'e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary': 'Momentary Guests', '0c9dfc91-6886-4962-872e-1259f7263bf1.momentary': 'Momentary For testing', '079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary': 'Momentary Scene Morning', '894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary': 'Momentary MVPS Backup full', 'a0a182be-735d-4122-aa22-9d54d0806022.momentary': 'Momentary MVPS Update blacklist', 'a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary': 'Momentary MVPS apt update', '33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary': 'Momentary MVPS ipset abuseipdb', 'cce01948-a4ce-41da-8906-7ef99fdad568.momentary': 'Momentary MVPS Umount NAS', '9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary': 'Momentary MVPS Backup db', '594b8a78-3786-48f7-bf24-f55e49451da0.momentary': 'Momentary MVPS Backup ispconfig', '16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary': 'Momentary MVPS Backup vmail', '51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary': 'Momentary MVPS clearlog', '6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary': 'Momentary MVPS Rspamd learn'}
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] dump(load):devices-meta={'Momentary Peter Early Up': {'device_id': '172f520c-a166-4252-88fc-579f98236a92.momentary'}, 'Momentary Early Sleep': {'device_id': '6b00964b-bd44-4b1c-a92b-2895a6747766.momentary'}, 'Momentary Guests': {'device_id': 'e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary'}, 'Momentary For testing': {'device_id': '0c9dfc91-6886-4962-872e-1259f7263bf1.momentary'}, 'Momentary Scene Morning': {'device_id': '079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary'}, 'Momentary MVPS Backup full': {'device_id': '894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary'}, 'Momentary MVPS Update blacklist': {'device_id': 'a0a182be-735d-4122-aa22-9d54d0806022.momentary'}, 'Momentary MVPS apt update': {'device_id': 'a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary'}, 'Momentary MVPS ipset abuseipdb': {'device_id': '33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary'}, 'Momentary MVPS Umount NAS': {'device_id': 'cce01948-a4ce-41da-8906-7ef99fdad568.momentary'}, 'Momentary MVPS Backup db': {'device_id': '9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary'}, 'Momentary MVPS Backup ispconfig': {'device_id': '594b8a78-3786-48f7-bf24-f55e49451da0.momentary'}, 'Momentary MVPS Backup vmail': {'device_id': '16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary'}, 'Momentary MVPS clearlog': {'device_id': '51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary'}, 'Momentary MVPS Rspamd learn': {'device_id': '6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary'}}
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] dump(load):orphaned-devices={}
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] dump(load):switches={'76f430e7-b4fc-4797-b2ce-90acf12ec21c.momentary': {'name': 'Momentary Peter Early Up', 'mode': 'on', 'cancellable': True, 'toggle_for': 18000, 'device_id': '172f520c-a166-4252-88fc-579f98236a92.momentary', 'entity_id': 'switch.momentary_peter_early_up'}, '714725dc-776e-464f-838e-09ce4ca8d077.momentary': {'name': 'Momentary Early Sleep', 'mode': 'on', 'cancellable': True, 'toggle_for': 18000, 'device_id': '6b00964b-bd44-4b1c-a92b-2895a6747766.momentary', 'entity_id': 'switch.momentary_early_sleep'}, 'e5720ccd-faeb-44b9-b9f8-1570efe74191.momentary': {'name': 'Momentary Guests', 'mode': 'on', 'cancellable': True, 'toggle_for': 32400, 'device_id': 'e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary', 'entity_id': 'switch.momentary_guests'}, 'e16f6b10-a6bf-4887-8200-2f43ae67e95d.momentary': {'name': 'Momentary For testing', 'mode': 'on', 'cancellable': True, 'toggle_for': 5, 'device_id': '0c9dfc91-6886-4962-872e-1259f7263bf1.momentary', 'entity_id': 'switch.momentary_for_testing'}, 'ca204868-f9f0-4165-9d86-7bb0fa186d40.momentary': {'name': 'Momentary Scene Morning', 'mode': 'on', 'cancellable': True, 'toggle_for': 14400, 'device_id': '079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary', 'entity_id': 'switch.momentary_scene_morning'}, '057d6eca-ad1a-4d0e-b19c-66e728b8170b.momentary': {'name': 'Momentary MVPS Backup full', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary', 'entity_id': 'switch.momentary_mvps_backup_full'}, 'b8e199ac-619d-4b83-9fd8-9a31584fe2ff.momentary': {'name': 'Momentary MVPS Update blacklist', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': 'a0a182be-735d-4122-aa22-9d54d0806022.momentary', 'entity_id': 'switch.momentary_mvps_update_blacklist'}, '490ee4f2-b193-4fdd-a73c-67ba50008c16.momentary': {'name': 'Momentary MVPS apt update', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': 'a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary', 'entity_id': 'switch.momentary_mvps_apt_update'}, 'aeafc93d-2469-4f63-b447-f057af7110e3.momentary': {'name': 'Momentary MVPS ipset abuseipdb', 'cancellable': True, 'toggle_for': 30, 'device_id': '33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary', 'entity_id': 'switch.momentary_mvps_ipset_abuseipdb'}, 'cac2d3dc-4775-4d1f-919a-9fe89f62b4e9.momentary': {'name': 'Momentary MVPS Umount NAS', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': 'cce01948-a4ce-41da-8906-7ef99fdad568.momentary', 'entity_id': 'switch.momentary_mvps_umount_nas'}, 'dee19a43-01f4-4e02-9a1a-061985ac6232.momentary': {'name': 'Momentary MVPS Backup db', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary', 'entity_id': 'switch.momentary_mvps_backup_db'}, '5de5e731-3cea-4ea7-812e-5ce9c863ae16.momentary': {'name': 'Momentary MVPS Backup ispconfig', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '594b8a78-3786-48f7-bf24-f55e49451da0.momentary', 'entity_id': 'switch.momentary_mvps_backup_ispconfig'}, 'cb3c1a92-e518-46c7-b93a-168ee2a95358.momentary': {'name': 'Momentary MVPS Backup vmail', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary', 'entity_id': 'switch.momentary_mvps_backup_vmail'}, 'b9b397d7-b8f9-4a71-97e3-0eb1a94fc555.momentary': {'name': 'Momentary MVPS clearlog', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary', 'entity_id': 'switch.momentary_mvps_clearlog'}, 'a29c4c3a-4187-46aa-ac9d-ee52ad58f9fa.momentary': {'name': 'Momentary MVPS Rspamd learn', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary', 'entity_id': 'switch.momentary_mvps_rspamd_learn'}}
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary.cfg] dump(load):switches-meta={'Momentary Peter Early Up': {'unique_id': '76f430e7-b4fc-4797-b2ce-90acf12ec21c.momentary', 'entity_id': 'switch.momentary_peter_early_up'}, 'Momentary Early Sleep': {'unique_id': '714725dc-776e-464f-838e-09ce4ca8d077.momentary', 'entity_id': 'switch.momentary_early_sleep'}, 'Momentary Guests': {'unique_id': 'e5720ccd-faeb-44b9-b9f8-1570efe74191.momentary', 'entity_id': 'switch.momentary_guests'}, 'Momentary For testing': {'unique_id': 'e16f6b10-a6bf-4887-8200-2f43ae67e95d.momentary', 'entity_id': 'switch.momentary_for_testing'}, 'Momentary Scene Morning': {'unique_id': 'ca204868-f9f0-4165-9d86-7bb0fa186d40.momentary', 'entity_id': 'switch.momentary_scene_morning'}, 'Momentary MVPS Backup full': {'unique_id': '057d6eca-ad1a-4d0e-b19c-66e728b8170b.momentary', 'entity_id': 'switch.momentary_mvps_backup_full'}, 'Momentary MVPS Update blacklist': {'unique_id': 'b8e199ac-619d-4b83-9fd8-9a31584fe2ff.momentary', 'entity_id': 'switch.momentary_mvps_update_blacklist'}, 'Momentary MVPS apt update': {'unique_id': '490ee4f2-b193-4fdd-a73c-67ba50008c16.momentary', 'entity_id': 'switch.momentary_mvps_apt_update'}, 'Momentary MVPS ipset abuseipdb': {'unique_id': 'aeafc93d-2469-4f63-b447-f057af7110e3.momentary', 'entity_id': 'switch.momentary_mvps_ipset_abuseipdb'}, 'Momentary MVPS Umount NAS': {'unique_id': 'cac2d3dc-4775-4d1f-919a-9fe89f62b4e9.momentary', 'entity_id': 'switch.momentary_mvps_umount_nas'}, 'Momentary MVPS Backup db': {'unique_id': 'dee19a43-01f4-4e02-9a1a-061985ac6232.momentary', 'entity_id': 'switch.momentary_mvps_backup_db'}, 'Momentary MVPS Backup ispconfig': {'unique_id': '5de5e731-3cea-4ea7-812e-5ce9c863ae16.momentary', 'entity_id': 'switch.momentary_mvps_backup_ispconfig'}, 'Momentary MVPS Backup vmail': {'unique_id': 'cb3c1a92-e518-46c7-b93a-168ee2a95358.momentary', 'entity_id': 'switch.momentary_mvps_backup_vmail'}, 'Momentary MVPS clearlog': {'unique_id': 'b9b397d7-b8f9-4a71-97e3-0eb1a94fc555.momentary', 'entity_id': 'switch.momentary_mvps_clearlog'}, 'Momentary MVPS Rspamd learn': {'unique_id': 'a29c4c3a-4187-46aa-ac9d-ee52ad58f9fa.momentary', 'entity_id': 'switch.momentary_mvps_rspamd_learn'}}
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary] would try to add device 172f520c-a166-4252-88fc-579f98236a92.momentary/Momentary Peter Early Up
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary] would try to add device 6b00964b-bd44-4b1c-a92b-2895a6747766.momentary/Momentary Early Sleep
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary] would try to add device e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary/Momentary Guests
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary] would try to add device 0c9dfc91-6886-4962-872e-1259f7263bf1.momentary/Momentary For testing
2025-06-12 08:48:52.939 DEBUG (MainThread) [custom_components.momentary] would try to add device 079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary/Momentary Scene Morning
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary/Momentary MVPS Backup full
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device a0a182be-735d-4122-aa22-9d54d0806022.momentary/Momentary MVPS Update blacklist
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary/Momentary MVPS apt update
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary/Momentary MVPS ipset abuseipdb
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device cce01948-a4ce-41da-8906-7ef99fdad568.momentary/Momentary MVPS Umount NAS
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary/Momentary MVPS Backup db
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 594b8a78-3786-48f7-bf24-f55e49451da0.momentary/Momentary MVPS Backup ispconfig
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary/Momentary MVPS Backup vmail
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary/Momentary MVPS clearlog
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] would try to add device 6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary/Momentary MVPS Rspamd learn
2025-06-12 08:48:52.940 DEBUG (MainThread) [custom_components.momentary] update hass data {'Switches': {'devices': {'172f520c-a166-4252-88fc-579f98236a92.momentary': 'Momentary Peter Early Up', '6b00964b-bd44-4b1c-a92b-2895a6747766.momentary': 'Momentary Early Sleep', 'e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary': 'Momentary Guests', '0c9dfc91-6886-4962-872e-1259f7263bf1.momentary': 'Momentary For testing', '079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary': 'Momentary Scene Morning', '894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary': 'Momentary MVPS Backup full', 'a0a182be-735d-4122-aa22-9d54d0806022.momentary': 'Momentary MVPS Update blacklist', 'a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary': 'Momentary MVPS apt update', '33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary': 'Momentary MVPS ipset abuseipdb', 'cce01948-a4ce-41da-8906-7ef99fdad568.momentary': 'Momentary MVPS Umount NAS', '9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary': 'Momentary MVPS Backup db', '594b8a78-3786-48f7-bf24-f55e49451da0.momentary': 'Momentary MVPS Backup ispconfig', '16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary': 'Momentary MVPS Backup vmail', '51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary': 'Momentary MVPS clearlog', '6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary': 'Momentary MVPS Rspamd learn'}, 'switches': {'76f430e7-b4fc-4797-b2ce-90acf12ec21c.momentary': {'name': 'Momentary Peter Early Up', 'mode': 'on', 'cancellable': True, 'toggle_for': 18000, 'device_id': '172f520c-a166-4252-88fc-579f98236a92.momentary', 'entity_id': 'switch.momentary_peter_early_up'}, '714725dc-776e-464f-838e-09ce4ca8d077.momentary': {'name': 'Momentary Early Sleep', 'mode': 'on', 'cancellable': True, 'toggle_for': 18000, 'device_id': '6b00964b-bd44-4b1c-a92b-2895a6747766.momentary', 'entity_id': 'switch.momentary_early_sleep'}, 'e5720ccd-faeb-44b9-b9f8-1570efe74191.momentary': {'name': 'Momentary Guests', 'mode': 'on', 'cancellable': True, 'toggle_for': 32400, 'device_id': 'e769fa46-1989-4325-a2c1-e1da0d1847b4.momentary', 'entity_id': 'switch.momentary_guests'}, 'e16f6b10-a6bf-4887-8200-2f43ae67e95d.momentary': {'name': 'Momentary For testing', 'mode': 'on', 'cancellable': True, 'toggle_for': 5, 'device_id': '0c9dfc91-6886-4962-872e-1259f7263bf1.momentary', 'entity_id': 'switch.momentary_for_testing'}, 'ca204868-f9f0-4165-9d86-7bb0fa186d40.momentary': {'name': 'Momentary Scene Morning', 'mode': 'on', 'cancellable': True, 'toggle_for': 14400, 'device_id': '079415a1-7ff9-4b29-97e2-caf7c4c10fe7.momentary', 'entity_id': 'switch.momentary_scene_morning'}, '057d6eca-ad1a-4d0e-b19c-66e728b8170b.momentary': {'name': 'Momentary MVPS Backup full', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '894b36fa-9bc6-416a-b2f1-64eb87a6a999.momentary', 'entity_id': 'switch.momentary_mvps_backup_full'}, 'b8e199ac-619d-4b83-9fd8-9a31584fe2ff.momentary': {'name': 'Momentary MVPS Update blacklist', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': 'a0a182be-735d-4122-aa22-9d54d0806022.momentary', 'entity_id': 'switch.momentary_mvps_update_blacklist'}, '490ee4f2-b193-4fdd-a73c-67ba50008c16.momentary': {'name': 'Momentary MVPS apt update', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': 'a59d8fd1-5543-4828-b237-487d3f0c56e6.momentary', 'entity_id': 'switch.momentary_mvps_apt_update'}, 'aeafc93d-2469-4f63-b447-f057af7110e3.momentary': {'name': 'Momentary MVPS ipset abuseipdb', 'cancellable': True, 'toggle_for': 30, 'device_id': '33cfa1f5-2bb6-4f75-b4ce-3f96c0919358.momentary', 'entity_id': 'switch.momentary_mvps_ipset_abuseipdb'}, 'cac2d3dc-4775-4d1f-919a-9fe89f62b4e9.momentary': {'name': 'Momentary MVPS Umount NAS', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': 'cce01948-a4ce-41da-8906-7ef99fdad568.momentary', 'entity_id': 'switch.momentary_mvps_umount_nas'}, 'dee19a43-01f4-4e02-9a1a-061985ac6232.momentary': {'name': 'Momentary MVPS Backup db', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '9baa0639-aa37-497a-ae6a-dff9f3beb574.momentary', 'entity_id': 'switch.momentary_mvps_backup_db'}, '5de5e731-3cea-4ea7-812e-5ce9c863ae16.momentary': {'name': 'Momentary MVPS Backup ispconfig', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '594b8a78-3786-48f7-bf24-f55e49451da0.momentary', 'entity_id': 'switch.momentary_mvps_backup_ispconfig'}, 'cb3c1a92-e518-46c7-b93a-168ee2a95358.momentary': {'name': 'Momentary MVPS Backup vmail', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '16a4784f-d01b-4f6f-a08c-e2023ff0594b.momentary', 'entity_id': 'switch.momentary_mvps_backup_vmail'}, 'b9b397d7-b8f9-4a71-97e3-0eb1a94fc555.momentary': {'name': 'Momentary MVPS clearlog', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '51d8f422-4ca6-4e02-ab39-d4bb85992ffb.momentary', 'entity_id': 'switch.momentary_mvps_clearlog'}, 'a29c4c3a-4187-46aa-ac9d-ee52ad58f9fa.momentary': {'name': 'Momentary MVPS Rspamd learn', 'mode': 'on', 'cancellable': True, 'toggle_for': 30, 'device_id': '6db45ec7-455f-4c59-b9e5-0ddec32d65ee.momentary', 'entity_id': 'switch.momentary_mvps_rspamd_learn'}}, 'file_name': '/config/integrations/momentary.yaml'}}
2025-06-12 08:48:52.940 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Switches - momentary for momentary
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 749, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/momentary/__init__.py", line 135, in async_setup_entry
    await hass.config_entries.async_forward_entry_setup(entry, Platform.SWITCH)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setup'. Did you mean: 'async_forward_entry_setups'?
```

**Comment by poudenes** [comment]
Same... Many automations are using this integration :)
